matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
    - os: osx
      osx_image: xcode8
      compiler: clang
language: cpp
addons:
  apt:
    packages:
      - libc6-dev
      - libc6-dev-i386
      - g++-multilib
      - clang-3.6
install:
  - pip install --upgrade --user xlsxwriter pycrypto
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=/usr/bin/clang++-3.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=/usr/bin/clang-3.6; fi
script:
  - ./build.sh
